### ISSUE TITLE
When do you support AR9344?

### ISSUE THREAD

**Issue by zhaojh329** [olerem/barebox#1]
When do you support AR9344?

**Comment by olerem** [comment]
There is already a version to play with it, it can Boot from SPI Flash. Right now i push working parts upstream to barebox and then continue to work on it. What is the background of your question?

**Comment by zhaojh329** [comment]
Openwrt/Lede

**Comment by olerem** [comment]
This is my target too. Do you plan to work on kernel or barebox?
Some of patches are upstream now:
https://git.pengutronix.de/cgit/barebox/log/?h=next
more patches are on the way.

**Comment by olerem** [comment]
From HW point of view, AR9344 support for Barebox is done. It can boot from spi, init RAM and use Ethernet. We will probably need to add ART partition support and use this information on Barebox. But it can be done later.
The patches are on the way upstream http://lists.infradead.org/pipermail/barebox/2017-August/031011.html
I need to take over this patches: https://github.com/frantony/barebox/commits/20170319.mips-malta-elf-linux
to make proper kernel boot on mips version of barebox possible.
Testing and feedbacks are welcome.

**Comment by zhaojh329** [comment]
Do you plan to implement the web update firmware?

**Comment by zhaojh329** [comment]
Do you plan to implement web update firmware? That is, accessing barebox through a browser to update firmware.

**Comment by olerem** [comment]
Currently not in my todo list. But patches are welcome. Please note, the code in u-boot_mod project is a BSD license and can't be upstreamed  to barebox or u-boot since they are GPL.
https://github.com/pepe2k/u-boot_mod/blob/master/u-boot/httpd/main.c

**Comment by zhaojh329** [comment]
Barebox has implemented UDP, and if you can implement TCP, that's fine.

**Comment by olerem** [comment]
yes. My target is to upstream ar9344 to the linux kernel. Implementing TCP for Barebox is completely different work field.

**Comment by zhaojh329** [comment]
For MIPS, Barebox does not support booting uimage currently , do you plan to implement it?



jianhuizhao329@gmail.com
 
From: Oleksij Rempel
Date: 2017-08-28 16:08
To: olerem/barebox
CC: zhaojianhui; Author
Subject: Re: [olerem/barebox] When do you support AR9344? (#1)
yes. My target is to upstream ar9344 to the linux kernel. Implementing TCP for Barebox is completely different work field.

**Comment by olerem** [comment]
Yes, i think about this.
some of kernel booting is already implemented here:
https://github.com/frantony/barebox/commits/20170319.mips-malta-elf-linux
The problem with MIPS, there are bazillion ways to boot it. Each company seems to make own.

**Comment by olerem** [comment]
and before doing kernel boot, i need to fix cache problems:
https://github.com/olerem/barebox/tree/v2017.09.0/board/tplink-2017.09.19
without this patches i can't even boot barebox from barebox.
